import React, { useState, useEffect } from 'react';
import { Applicant, DocumentFile } from '../types';
import { ArrowLeftIcon } from './Icons';
import PieChart from './PieChart';
import DocumentViewer from './DocumentViewer';
import FileUpload from './FileUpload';

interface ApplicantDashboardProps {
    applicant: Applicant;
    onBack: () => void;
}

const ApplicantDashboard: React.FC<ApplicantDashboardProps> = ({ applicant, onBack }) => {
    const [uploadedFiles, setUploadedFiles] = useState<DocumentFile[]>([]);

    // Scroll to top when this page loads
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const handleFilesChange = (files: File[]) => {
        const wrapped = files.map((file, index) => ({
            id: `${file.name}-${index}-${Date.now()}`,
            file,
        }));
        setUploadedFiles(prev => [...prev, ...wrapped]);
    };

    const handleRemoveFile = (id: string) => {
        setUploadedFiles(prev => prev.filter(f => f.id !== id));
    };

    const getStatusStyles = (status: 'pass' | 'fail' | 'warning') => {
        switch (status) {
            case 'pass':
                return {
                    dot: 'bg-green-500',
                    text: 'text-green-700',
                    label: 'Pass',
                };
            case 'fail':
                return {
                    dot: 'bg-red-500',
                    text: 'text-red-700',
                    label: 'Fail',
                };
            case 'warning':
                return {
                    dot: 'bg-yellow-500',
                    text: 'text-yellow-700',
                    label: 'Review',
                };
            default:
                return {
                    dot: 'bg-neutral-400',
                    text: 'text-neutral-700',
                    label: '',
                };
        }
    };

    return (
        <div className="animate-fade-in">
            <button
                onClick={onBack}
                className="flex items-center gap-2 text-primary-dark font-semibold mb-6 hover:underline"
            >
                <ArrowLeftIcon className="h-5 w-5" />
                Back to all applicants
            </button>

            <div className="space-y-6">
                {/* Header */}
                <div className="bg-white p-6 rounded-lg shadow-lg">
                    <h2 className="text-3xl font-bold text-neutral-900">{applicant.name}</h2>
                    <p className="text-neutral-500 mt-1">
                        Application Date: {applicant.applicationDate}
                    </p>
                </div>

                {/* Main Content Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Risk Assessment */}
                    <div className="lg:col-span-1 bg-white p-6 rounded-lg shadow-lg flex flex-col items-center">
                        <h3 className="text-xl font-bold text-neutral-800 mb-4">Risk Assessment</h3>
                        <PieChart score={applicant.riskScore} size={200} />
                        <p className="text-center text-neutral-600 mt-4">
                            Based on the provided documents, the applicant has a
                            <span className="font-bold"> {Math.round(applicant.riskScore * 100)}%</span>
                            risk score.
                        </p>
                    </div>

                    {/* AI Summary */}
                    <div className="lg:col-span-2 bg-white p-6 rounded-lg shadow-lg">
                        <h3 className="text-xl font-bold text-neutral-800 mb-4">AI Summary</h3>
                        <p className="text-neutral-700 leading-relaxed">{applicant.summary}</p>
                    </div>
                </div>

                {/* Fraud & Consistency Checks */}
                <div className="bg-white p-6 rounded-lg shadow-lg">
                    <h3 className="text-xl font-bold text-neutral-800 mb-2">
                        Fraud &amp; Consistency Checks
                    </h3>
                    <p className="text-sm text-neutral-600 mb-4">
                        These checks are generated by the fraud detection engine based on cross-document
                        analysis and external data sources. They help explain why the applicant&apos;s risk
                        score is low, medium, or high.
                    </p>

                    {applicant.fraudChecks && applicant.fraudChecks.length > 0 ? (
                        <ul className="space-y-3">
                            {applicant.fraudChecks.map((check, index) => {
                                const styles = getStatusStyles(check.status);
                                return (
                                    <li
                                        key={index}
                                        className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 border-b border-neutral-100 pb-2 last:border-b-0"
                                    >
                                        <div className="flex items-center gap-2">
                                            <span className={`h-3 w-3 rounded-full ${styles.dot}`} />
                                            <span className="text-sm font-medium text-neutral-800">
                                                {check.label}
                                            </span>
                                        </div>
                                        <div className="text-xs sm:text-sm">
                                            <span className={`font-semibold ${styles.text}`}>
                                                {styles.label}
                                            </span>
                                            {check.details && (
                                                <span className="text-neutral-600 block sm:inline sm:ml-2">
                                                    {check.details}
                                                </span>
                                            )}
                                        </div>
                                    </li>
                                );
                            })}
                        </ul>
                    ) : (
                        <p className="text-sm text-neutral-500">
                            No fraud or consistency issues have been flagged for this applicant.
                        </p>
                    )}
                </div>

                {/* Upload Documents */}
                <div className="bg-white p-6 rounded-lg shadow-lg">
                    <h3 className="text-xl font-bold text-neutral-800 mb-2">
                        Upload applicant documents
                    </h3>
                    <p className="text-sm text-neutral-600 mb-4">
                        Select one or more PDF files (bank statements, paystubs, forms) to attach
                        for this applicant. In the future these files will be sent to the backend
                        for OCR and fraud analysis.
                    </p>
                    <FileUpload
                        title="Upload PDF documents"
                        description="Drag and drop or click to select PDF files."
                        onFilesChange={handleFilesChange}
                        files={uploadedFiles}
                        onRemoveFile={handleRemoveFile}
                        multiple={true}
                        accept=".pdf,application/pdf"
                    />
                </div>

                {/* Documents */}
                <div className="bg-white p-6 rounded-lg shadow-lg">
                    <DocumentViewer documents={applicant.documents} />
                </div>
            </div>
        </div>
    );
};

export default ApplicantDashboard;
